# Generated by Django 4.2.18 on 2025-01-28 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='otp',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
