# Generated by Django 4.2.18 on 2025-01-28 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_student_otp'),
    ]

    operations = [
        migrations.CreateModel(
            name='CollegeGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(default='general', max_length=50)),
                ('members', models.ManyToManyField(related_name='CollegeGroup', to='main.student')),
            ],
        ),
    ]
