# Generated by Django 4.2.18 on 2025-01-29 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_expense_amount_alter_expense_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='upi_id',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
